# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/mitch/Documents/School/ProjectRetroGame_Software/Basys3 Software/RetroSkiGame/RetroSkiGame.srcs/sources_1/ip/Ernie/Ernie.xci
# IP: The module: 'Ernie' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mitch/Documents/School/ProjectRetroGame_Software/Basys3 Software/RetroSkiGame/RetroSkiGame.srcs/sources_1/ip/Ernie/Ernie_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ernie'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/mitch/Documents/School/ProjectRetroGame_Software/Basys3 Software/RetroSkiGame/RetroSkiGame.srcs/sources_1/ip/Ernie/Ernie.xci
# IP: The module: 'Ernie' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mitch/Documents/School/ProjectRetroGame_Software/Basys3 Software/RetroSkiGame/RetroSkiGame.srcs/sources_1/ip/Ernie/Ernie_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ernie'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
